#!/bin/sh

# credits
# https://github.com/NicholasFeldman/dotfiles/blob/master/polybar/.config/polybar/spotify.sh

#main() {
#  if ! pgrep -x spotify >/dev/null; then
#    echo ""; exit
#  fi
#
#  cmd="org.freedesktop.DBus.Properties.Get"
#  domain="org.mpris.MediaPlayer2"
#  path="/org/mpris/MediaPlayer2"
#
#  meta=$(dbus-send --print-reply --dest=${domain}.spotify \
#    /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:${domain}.Player string:Metadata)
#
#  artist=$(echo "$meta" | sed -nr '/xesam:artist"/,+2s/^ +string "(.*)"$/\1/p' | tail -1  | sed "s/\&/+/g")
#  album=$(echo "$meta" | sed -nr '/xesam:album"/,+2s/^ +variant +string "(.*)"$/\1/p' | tail -1)
#  title=$(echo "$meta" | sed -nr '/xesam:title"/,+2s/^ +variant +string "(.*)"$/\1/p' | tail -1 | sed "s/\&/+/g")
#
#  echo " ${*:-%artist% - %title%}" | sed "s/%artist%/$artist/g;s/%title%/$title/g;s/%album%/$album/g"i | sed 's/&/\\&/g'
#}

#main "$@"

# { echo "$(spotify-now -i " <b>%title" -e "" -p " paused" | awk -v len=40 '{ if (length($0) > len) print substr($0, 1, len-3) "..."; else print; }' | tr -d '&' | awk '{print $0 "</b>"}')"; echo "$(spotify-now -i '%artist' -p ' ' -e ' ')"; } | tr "\n" " "

{ echo "$(playerctl metadata title | awk -v len=15 '{ if (length($0) > len) print substr($0, 1, len-3) "."; else print; }' | tr -d '&' | awk '{print $0}')"; echo "$(playerctl metadata artist | awk -v len=15 '{ if (length($0) > len) print substr($0, 1, len-3) "."; else print; }')"; } | tr "\n" " "

#{ echo "$(spotify-now -i " %title" -e "" -p " paused" | awk -v len=25 '{ if (length($0) > len) print substr($0, 1, len-3) "..."; else print; }' | tr -d '&' | awk '{print $0}')"; echo "$(spotify-now -i '~%artist' -p ' ' -e ' ' | awk -v len=15 '{ if (length($0) > len) print substr($0, 1, len-3) "..."; else print; }' )"; } | tr "\n" " "

#case "$BLOCK_BUTTON" in
#  1) exec playerctl previous ;; 
#  2) exec playerctl play-pause ;; 
#  3) exec playerctl next ;;
#  4) exec ~/.config/i3/pulseaudio-rofi --volume_up ;;
#  5) exec ~/.config/i3/pulseaudio-rofi --volume_down ;;
#esac
