#!/bin/bash

# I take this script from Anachron's i3blocks
# I only slightly modify this script to add an option to show icon, useful for my tint2 executor
# 'weather -i' = with icon, 'weather' = text only
# Cheers!
# Addy

# Open Weather Map API code, register to http://openweathermap.org to get one ;)
API_KEY="9170a2b7a34cf3fc3ef656926fd8de99"

# Check on http://openweathermap.org/find
#CITY_ID="your city id here"

URGENT_LOWER=0
URGENT_HIGHER=30

TEXT_SUNNY=""
TEXT_CLOUDY=""
TEXT_HAZE="⛅"
TEXT_RAINY=""
TEXT_STORM=""
TEXT_SNOW=""
TEXT_FOG=""
TEXT_NIGHT=""
TEXT_MISC=""

TEXT_SUNNY=""
TEXT_CLOUDY=""
TEXT_HAZE="⛅"
TEXT_RAINY=""
TEXT_STORM=""
TEXT_SNOW=""
TEXT_FOG=""
TEXT_NIGHT=""
TEXT_MISC=""

SYMBOL_CELSIUS="˚C"

#WEATHER_URL="http://api.openweathermap.org/data/2.5/weather?lat=-22,90&lon=-43,59&appid=9170a2b7a34cf3fc3ef656926fd8de99&units=metric"
#WEATHER_URL="http://api.openweathermap.org/data/2.5/weather?lat=-32,03&lon=-52,08&appid=9170a2b7a34cf3fc3ef656926fd8de99&units=metric"
WEATHER_URL="http://api.openweathermap.org/data/2.5/weather?id=3451138&appid=9170a2b7a34cf3fc3ef656926fd8de99"

#-32.03542432
#-52.1022132

WEATHER_INFO=$(wget --output-file=/tmp/logwget -qO- "${WEATHER_URL}")
WEATHER_MAIN=$(echo "${WEATHER_INFO}" | grep -o -e '\"main\":\"[a-Z]*\"' | awk -F ':' '{print $2}' | tr -d '"')
WEATHER_TEMP=$(echo "${WEATHER_INFO}" | grep -o -e '\"temp\":\-\?[0-9]*' | awk -F ':' '{print $2}' | tr -d '"')

if [[ "${WEATHER_MAIN}" = *Snow* ]]; then
	if  [[ $1 = "-i" ]]; then
    echo "${ICON_SNOW} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
	else
    echo "${TEXT_SNOW} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
	fi
elif [[ "${WEATHER_MAIN}" = *Rain* ]] || [[ "${WEATHER_MAIN}" = *Drizzle* ]]; then
	if  [[ $1 = "-i" ]]; then
    echo "${ICON_RAINY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
	else
    echo "${TEXT_RAINY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
	fi
elif [[ "${WEATHER_MAIN}" = *Cloud* ]]; then
	if  [[ $1 = "-i" ]]; then
    echo "${ICON_CLOUDY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
	else
    echo "${TEXT_CLOUDY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
	fi
elif [[ "${WEATHER_MAIN}" = *Haze* ]]; then
	if  [[ $1 = "-i" ]]; then
    echo "${ICON_HAZE} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
	else
    echo "${TEXT_HAZE} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
	fi
elif [[ "${WEATHER_MAIN}" = *Clear* ]]; then
	if  [[ $1 = "-i" ]]; then
    echo "${ICON_SUNNY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
	else
    echo "${TEXT_SUNNY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
	fi
elif [[ "${WEATHER_MAIN}" = *Fog* ]] || [[ "${WEATHER_MAIN}" = *Mist* ]]; then
	if  [[ $1 = "-i" ]]; then
    echo "${ICON_FOG} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
	else
    echo "${TEXT_FOG} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
	fi
elif [[ "${WEATHER_MAIN}" = *Thunderstorm* ]]; then
	if  [[ $1 = "-i" ]]; then
  	echo "${ICON_STORM} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
  	else
  	echo "${TEXT_STORM} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
  	fi
elif [[ "${WEATHER_MAIN}" = *Night* ]]; then
	if  [[ $1 = "-i" ]]; then
  	echo "${ICON_NIGHT} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
  	else
  	echo "${TEXT_NIGHT} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
  	fi
else
	if  [[ $1 = "-i" ]]; then
    echo "${ICON_MISC} ${WEATHER_MAIN} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
	else
    echo "${WEATHER_MAIN} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
	fi	
fi

if [[ "${WEATHER_TEMP}" -lt "${URGENT_LOWER}" ]] || [[ "${WEATHER_TEMP}" -gt "${URGENT_HIGHER}" ]]; then
  exit 33
fi
