#!/bin/sh

sink=0

volume_up() {
    pactl set-sink-mute @DEFAULT_SINK@ false ; pactl set-sink-volume @DEFAULT_SINK@ +5%
}

volume_down() {
    pactl set-sink-mute @DEFAULT_SINK@ false ; pactl set-sink-volume @DEFAULT_SINK@ -5%
}

mute() {
    pactl set-sink-mute @DEFAULT_SINK@ toggle
}

volume_print() {
    if pacmd list-sinks | grep active | head -n 1 | grep -q speaker; then
        icon="📢"
    elif pacmd list-sinks | grep active | head -n 1 | grep headphones; then
        icon="🎧"
    else
        #icon=""
        icon="🔊"
    fi

    #muted=$(pamixer --sink $sink --get-mute)
    muted=$(pamixer --get-mute)

    if [ "$muted" = true ]; then
        echo " --"
        #echo " --"
    else
        #echo "$icon $(pamixer --sink $sink --get-volume)%"
        echo "$icon $(pamixer --get-volume)%"
    fi
}

listen() {
    volume_print

    pactl subscribe | while read -r event; do
        if echo "$event" | grep -q "#$sink"; then
            volume_print
        fi
    done
}

case "$1" in
    --up)
        volume_up
        ;;
    --down)
        volume_down
        ;;
    --mute)
        volume_mute
        ;;
    *)
        listen
        ;;
esac
