#!/usr/bin/env bash

question=$(echo " Caffeine| Bloquear| Sair| Reiniciar| Desligar" | rofi -theme ~/.themes/arthur_power.rasi -sep "|" \
    -dmenu -i -p 'System: ' "" -width 40 -hide-scrollbar \ -line-padding 5 -padding 10 -lines 5 -color-enabled)

case $question in
	*Caffeine)
        sleep 1; xset s off -dpms && xautolock -exit
        ;;
    *Bloquear)
        xautolock -locknow && sleep 1
        ;;
    *Sair)
        #command -v gnome-session-quit 2>/dev/null 2>&1 || command -v session-logout >/dev/null 2>&1
        #xfce4-session-logout -l
        i3-msg exit
        ;;
    *Reiniciar)
        # bash -c "~/.local/bin/firefox-sync.sh cjyeb6td.default-release > /dev/null &" && systemctl reboot
        systemctl reboot
        # sudo -A shutdown -r now
        # bash -c "~/.local/bin/firefox-sync.sh cjyeb6td.default-release > /dev/null &" && loginctl reboot
        ;;
    *Desligar)
        systemctl poweroff
        # bash -c "~/.local/bin/firefox-sync.sh cjyeb6td.default-release > /dev/null &" && systemctl poweroff
        # sudo -A shutdown -P now
        # bash -c "~/.local/bin/firefox-sync.sh cjyeb6td.default-release > /dev/null &" && loginctl poweroff
        ;;
    *)
        exit 0  # do nothing on wrong response
        ;;
esac

